baseurl = "/"
relativeurls = false
languageCode = "en-us"
title = "Jianfeng Li | 李剑峰"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = "life2cloud"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true
rssLimit = 30

[permalinks]
    cn = "/cn/:year/:month/:slug/"
    en = "/en/:year/:month/:slug/"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/en/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.main]]
    name = "Vitae"
    url = "/en/vitae/"
    weight = 5
[[menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 6
[[menu.main]]
    name = "博客"
    url = "/cn/"
    weight = 7
[[menu.main]]
    name = "简历"
    url = "/cn/vitae/"
    weight = 8
[[menu.main]]
    name = "关于"
    url = "/cn/about/"
    weight = 9

[params]
    description = "Personal website of Jianfeng Li; 李剑峰的个人网站"
    disqusURL = "https://www.life2cloud.com"
    dateFormat = "2006/01/02"
    customCSS = ["css/custom.css", "css/share.min.css"]
    customJS = ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", 
                "js/fix-footnote.js", "js/math-code.js",
		"js/qrcode.js", "js/social-share.js", "js/busuanzi.pure.mini.js"]
    githubContentURL = "https://github.com/Miachol/life2cloud/edit/master/content/"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.social]
    github  = "Miachol"

    [params.author]
    en = "Jianfeng Li"
    cn = "李剑峰"

    [params.lang.edit]
    en = "Suggest an edit of this page"
    cn = "编辑本页"
 [blackfriday]
    extensionsmask = ["noIntraEmphasis"]
